name: deploy
on:
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: actions/checkout@v3

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.gcp_credentials }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v0"
        with:
          name: "projects/greg-finley/locations/us-central1/functions/security-demo"
          runtime: "python311"
          entry_point: "run"
          memory_mb: 128
          timeout: 30
          min_instances: 0
          max_instances: 1

